### ISSUE TITLE
NotImplementedError: Instruction 0xff not implemented

### ISSUE THREAD

**Issue by twkomp** [Osmose/snoboy#1]
the code is not working. every time i try to run the code, i get the error code `NotImplementedError: Instruction 0xff not implemented`.

**Comment by twkomp** [comment]
heres the full error:
`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 7, in main
    cpu.doInstruction()
  File "/home/thomas/Downloads/snoboy-master/snoboy/cpu.py", line 17, in doInstruction
    raise NotImplementedError("Instruction 0x%x not implemented"%opcode)
`
